"""The surface→scenario map (coverage.py's check consumes this).

Values are scenario ids: ``gate-N`` (the release-gate scenarios) or
the suite spec ids in scenarios.py (``a1``..``j4``). ``_prefix_rules``
cover whole families with one rule; ``_exclusions`` are justified
surfaces the unit/Qt suites already own (the design allows an
explicit, justified exclusion and nothing else).
"""
from __future__ import annotations

SCENARIO_MAP = {
    # The QML-facing verbs on the settings machine action (group I).
    "MoonrakerFollowerMachineAction.cancelTest": "i2",
    "MoonrakerFollowerMachineAction.clearCache": "i6",
    "MoonrakerFollowerMachineAction.insecureKeyWarning": "i2",
    "MoonrakerFollowerMachineAction.saveConfig": "i6",
    "MoonrakerFollowerMachineAction.testConnection": "i2",
    "MoonrakerFollowerMachineAction.validAuxInterval": "i3",
    "MoonrakerFollowerMachineAction.validConsoleInterval": "i3",
    "MoonrakerFollowerMachineAction.validPollInterval": "i3",
    "MoonrakerFollowerMachineAction.validRetryInterval": "i3",
    "MoonrakerFollowerMachineAction.validTranslation": "i4",
    "MoonrakerFollowerMachineAction.validUrl": "i1",
    "MoonrakerFollowerMachineAction.validZTolerance": "i4",
    # The model's user-intent verbs, per group.
    "MoonrakerMonitorModel.adjustZOffset": "g4",
    "MoonrakerMonitorModel.applyTemperaturePreset": "c1",
    "MoonrakerMonitorModel.calibrateBedMesh": "g2",
    "MoonrakerMonitorModel.cancelPrint": "g6",
    "MoonrakerMonitorModel.centerToolhead": "g2",
    "MoonrakerMonitorModel.clearFileFilters": "f1",
    "MoonrakerMonitorModel.clearFileSelection": "f1",
    "MoonrakerMonitorModel.clearBedMesh": "g2",
    "MoonrakerMonitorModel.clearConsoleHistory": "d3",
    "MoonrakerMonitorModel.clearZOffset": "g4",
    "MoonrakerMonitorModel.emergencyHoldReleased": "gate-10",
    "MoonrakerMonitorModel.emergencyHoldStarted": "gate-10",
    "MoonrakerMonitorModel.emergencyStopClick": "gate-10",
    "MoonrakerMonitorModel.excludeObject": "b11",
    "MoonrakerMonitorModel.extrude": "g4",
    "MoonrakerMonitorModel.firmwareRestart": "g9b",
    "MoonrakerMonitorModel.heatersOff": "g9b",
    "MoonrakerMonitorModel.home": "g2",
    "MoonrakerMonitorModel.homeAll": "g2",
    "MoonrakerMonitorModel.hostRestart": "g9b",
    "MoonrakerMonitorModel.improveEta": "h8",
    "MoonrakerMonitorModel.jog": "g1",
    "MoonrakerMonitorModel.klipperRestart": "g9b",
    "MoonrakerMonitorModel.loadBedMeshProfile": "g2",
    "MoonrakerMonitorModel.macroParameterDefinitions": "g5",
    "MoonrakerMonitorModel.motorsOff": "g2",
    "MoonrakerMonitorModel.openFileManager": "f1",
    "MoonrakerMonitorModel.openFrontend": "i7",
    "MoonrakerMonitorModel.pausePrint": "g6",
    "MoonrakerMonitorModel.previewFanSpeed": "c2",
    "MoonrakerMonitorModel.previewFlowFactor": "c2",
    "MoonrakerMonitorModel.previewLedBrightness": "c3",
    "MoonrakerMonitorModel.previewLedColor": "c3",
    "MoonrakerMonitorModel.previewPwmOutput": "c3",
    "MoonrakerMonitorModel.previewSpeedFactor": "c2",
    "MoonrakerMonitorModel.reconnect": "a8",
    "MoonrakerMonitorModel.refreshAll": "a7",
    "MoonrakerMonitorModel.refreshFileManager": "f1",
    "MoonrakerMonitorModel.refreshWebcams": "e1",
    "MoonrakerMonitorModel.resumePrint": "g6",
    "MoonrakerMonitorModel.runMacro": "g5",
    "MoonrakerMonitorModel.runQuadGantryLevel": "g2",
    "MoonrakerMonitorModel.saveConfig": "i6",
    "MoonrakerMonitorModel.selectWebcam": "e2",
    "MoonrakerMonitorModel.sendConsoleCommand": "d1",
    "MoonrakerMonitorModel.setBedMeshPreviewVisible": "h6",
    "MoonrakerMonitorModel.setConsoleExpanded": "d5",
    "MoonrakerMonitorModel.setConsoleHeight": "d5",
    "MoonrakerMonitorModel.setControlsCollapsed": "g8",
    "MoonrakerMonitorModel.setControlsLocked": "g8",
    "MoonrakerMonitorModel.setExtrudeDistance": "g4",
    "MoonrakerMonitorModel.setExtrudeSpeed": "g4",
    "MoonrakerMonitorModel.setFanSpeed": "c2",
    "MoonrakerMonitorModel.setFlowFactor": "c2",
    "MoonrakerMonitorModel.setInfoCollapsed": "d5",
    "MoonrakerMonitorModel.setJogDistance": "g1",
    "MoonrakerMonitorModel.setLedBrightness": "c3",
    "MoonrakerMonitorModel.setLedColor": "c3",
    "MoonrakerMonitorModel.setPositionMode": "g3",
    "MoonrakerMonitorModel.setPowerDevice": "g9",
    "MoonrakerMonitorModel.setPwmOutput": "c3",
    "MoonrakerMonitorModel.setSectionExpanded": "d5",
    "MoonrakerMonitorModel.setShowProbePoints": "h6b",
    "MoonrakerMonitorModel.setShowTemperaturePower": "c3",
    "MoonrakerMonitorModel.setShowTemperatureTargets": "c3",
    "MoonrakerMonitorModel.setSpeedFactor": "c2",
    "MoonrakerMonitorModel.setStatusCollapsed": "d5",
    "MoonrakerMonitorModel.setTemperatureSensorColor": "c3",
    "MoonrakerMonitorModel.setTemperatureSensorVisible": "c3",
    "MoonrakerMonitorModel.updateMoonrakerStatus": "b10",
    "MoonrakerMonitorModel.zToZero": "g2",
    "MoonrakerOutputDevice.acceptUpload": "f2",
    "MoonrakerOutputDevice.cancelUpload": "f2",
    "MoonrakerOutputDevice.leaveMonitorStage": "a9",
    "MoonrakerPrintFollower.confirmForceLoadCurrentPrint": "h2",
    "MoonrakerPrintFollower.toggleFollowingPause": "h3",
    # The interactive items by objectName.
    "moonrakerJogXPlus": "g1", "moonrakerJogXMinus": "g1",
    "moonrakerJogYPlus": "g1", "moonrakerJogYMinus": "g1",
    "moonrakerJogZPlus": "g1", "moonrakerJogZMinus": "g1",
    "moonrakerHomeX": "g2", "moonrakerHomeY": "g2", "moonrakerHomeZ": "g2",
    "moonrakerLockButton": "g8",
    "moonrakerEmergencyButton": "gate-10",
    "moonrakerConsoleInput": "d1", "moonrakerConsoleSend": "d1",
    "moonrakerM117Slot": "gate-3",
    "moonrakerPreviewActionPanelControls": "h3",
    "moonrakerEmptyPreviewLoadControl": "h2",
    "consoleResizeHandle": "d5", "consoleResizeArea": "d5",
    "infoPanel": "b1", "statusPanel": "b1",
    "cameraViewport": "e1", "cameraControls": "e2",
    "loadIndicatorContent": "h2",
    "printConfirmDialog": "f6", "slicerPopup": "f1", "modifiedPopup": "f1",
    "printTimePopup": "f1", "columnsPopup": "f1", "pageSizePopup": "f1",
    "gridHeader": "f1", "gridVertical": "f1", "columnResizeHandle": "f1",
    # The protocol endpoints: the simulator's contract test owns the
    # wire shapes; the scenarios drive them through the real UI.
    "status_endpoint": "b1", "websocket_endpoint": "a1",
    "metadata_endpoint": "f1", "download_endpoint": "h2",
    "print_start_endpoint": "f6", "delete_endpoint": "f3",
    "directory_delete_endpoint": "f4", "directory_create_endpoint": "f4",
    "move_endpoint": "f5", "server_info_endpoint": "b1",
    "objects_list_endpoint": "a1", "gcode_script_endpoint": "d1",
}

PREFIX_RULES = [
    # The file manager's verbs all ride the F-group scenarios.
    ("slot", "MoonrakerMonitorModel.file", "f1"),
    ("slot", "MoonrakerMonitorModel.toggleFile", "f1"),
    ("slot", "MoonrakerMonitorModel.setFile", "f1"),
    # The published keys by family.
    ("key", "console", "d1"),
    ("key", "camera", "e2"),
    ("key", "temperature", "c1"),
    ("key", "fan", "c2"),
    ("key", "fileManager", "f1"),
    ("key", "fileUpload", "f2"),
    ("key", "filePrint", "f6"),
    ("key", "fileDelete", "f3"),
    ("key", "fileRename", "f5"),
    ("key", "bedMesh", "h6"),
    ("key", "jog", "g1"),
    ("key", "extrude", "g4"),
    ("key", "monitor", "b2"),
    ("key", "filament", "b9"),
    ("key", "endstop", "c5"),
    ("key", "mcu", "c4"),
    ("key", "macro", "g5"),
    ("key", "powerDevices", "g9"),
    ("key", "emergency", "gate-10"),
    ("key", "controls", "g8"),
    ("key", "infoCollapsed", "d5"),
    ("key", "statusCollapsed", "d5"),
    ("key", "sectionExpandedMap", "d5"),
    ("key", "improvingEta", "h8"),
    ("key", "improveEta", "h8"),
    ("key", "showProbePoints", "h6b"),
    ("key", "saveConfig", "i6"),
    ("key", "canSaveConfig", "i6"),
    ("key", "webcamNames", "e2"),
    ("key", "activeWebcamIndex", "e2"),
    ("key", "speedFactorPercent", "c2"),
    ("key", "flowFactorPercent", "c2"),
    ("key", "ledItems", "c3"),
    ("key", "pwmOutputItems", "c3"),
    ("key", "fanControlItems", "c2"),
    ("key", "fanItems", "c2"),
    ("key", "filamentSensorItems", "c4"),
    ("key", "excludeObjectItems", "b11"),
    ("key", "zOffset", "g4"),
    ("key", "homedAxes", "b8"),
    ("key", "positionMode", "g3"),
    ("key", "klippyState", "b1"),
    ("key", "klipperVersion", "b1"),
    ("key", "moonrakerVersion", "b1"),
    ("key", "cpuTemperature", "c4"),
    ("key", "hostLoad", "c4"),
    ("key", "memoryAvailable", "c4"),
    ("key", "hasBedMesh", "h6"),
    ("key", "hasQuadGantryLevel", "g2"),
    ("key", "printActive", "b1"),
    ("key", "canPausePrint", "g6"),
    ("key", "canResumePrint", "g6"),
    ("key", "canCancelPrint", "g6"),
    ("key", "actionBusy", "b10"),
    ("key", "actionStatus", "b10"),
    ("key", "connectionDetail", "a9"),
    ("key", "canApplyTemperaturePreset", "c1"),
    ("key", "temperaturePresetItems", "c1"),
    ("key", "temperaturePresetNames", "c1"),
    ("key", "canRunSetup", "i2"),
]

EXCLUSIONS = {
    # British-spelling formatting is a pure function of the locale —
    # unit-tested in test_monitor, invisible to scenarios.
    "britishSpelling": "unit-tested: test_monitor.py (locale formatting)",
    # The console's resize GESTURE: no synthetic drag drives a QML
    # MouseArea's grab under Xvfb (QTest moves carry no button state,
    # injected moves never register as position changes). The commit
    # handler's model call is covered by d5 via setConsoleHeight; the
    # gesture itself stays unit/QML-covered.
    "consoleResizeHandle": "d5 covers the commit via setConsoleHeight; the synthetic drag cannot drive a QML MouseArea grab",
    "consoleResizeArea": "d5 covers the commit via setConsoleHeight; the synthetic drag cannot drive a QML MouseArea grab",
    # The lock button's position inside the Loader-built dashboard is
    # unreachable by the harness's item walk on every boot; g8 covers
    # the lock's model path via setControlsLocked in both directions.
    "moonrakerLockButton": "g8 covers the lock via setControlsLocked; the button is unreachable in the Loader-built dashboard",
}
